language: julia
os:
    - linux
    - osx
julia:
    # O.6 is nominally supported on this branch, but is too complex to test
    # when Project.toml is present. Be cautious if it's ever necessary to
    # tag a new 0.18 release in METADATA.
    - 0.7
    - 1.0
    - nightly
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libgmp-dev
        - libglpk-dev
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia --project=. -e 'using Pkg; Pkg.build()'
    - julia --project=. -e 'using Pkg; Pkg.test()'
    - julia --project=. -e 'using Pkg; Pkg.instantiate()'
    - julia --project=. test/hygiene.jl
    - julia --project=. -e 'using Pkg; Pkg.add("Ipopt")' # Needed for runhs.jl.
    - julia --project=. test/hockschittkowski/runhs.jl
